
// This file has been generated by the GUI designer. Do not modify.

public partial class GameWindow
{
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Button button8;
	private global::Gtk.Button o1;
	private global::Gtk.Button o2;
	private global::Gtk.Button o3;
	private global::Gtk.Button o4;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Label txt;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget GameWindow
		this.Name = "GameWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Window");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child GameWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button8 = new global::Gtk.Button ();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.fixed2.Add (this.button8);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.button8]));
		w1.X = 47;
		w1.Y = 264;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.o1 = new global::Gtk.Button ();
		this.o1.CanFocus = true;
		this.o1.Name = "o1";
		this.o1.UseUnderline = true;
		this.o1.Label = global::Mono.Unix.Catalog.GetString ("Option 1");
		this.fixed2.Add (this.o1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.o1]));
		w2.X = 335;
		w2.Y = 26;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.o2 = new global::Gtk.Button ();
		this.o2.CanFocus = true;
		this.o2.Name = "o2";
		this.o2.UseUnderline = true;
		this.o2.Label = global::Mono.Unix.Catalog.GetString ("Option 2");
		this.fixed2.Add (this.o2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.o2]));
		w3.X = 336;
		w3.Y = 61;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.o3 = new global::Gtk.Button ();
		this.o3.CanFocus = true;
		this.o3.Name = "o3";
		this.o3.UseUnderline = true;
		this.o3.Label = global::Mono.Unix.Catalog.GetString ("Option 3");
		this.fixed2.Add (this.o3);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.o3]));
		w4.X = 334;
		w4.Y = 96;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.o4 = new global::Gtk.Button ();
		this.o4.CanFocus = true;
		this.o4.Name = "o4";
		this.o4.UseUnderline = true;
		this.o4.Label = global::Mono.Unix.Catalog.GetString ("Option 4");
		this.fixed2.Add (this.o4);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.o4]));
		w5.X = 335;
		w5.Y = 127;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("HP:");
		this.fixed2.Add (this.label1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label1]));
		w6.X = 70;
		w6.Y = 7;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("00");
		this.fixed2.Add (this.label2);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
		w7.X = 93;
		w7.Y = 8;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.txt = new global::Gtk.Label ();
		this.txt.WidthRequest = 227;
		this.txt.HeightRequest = 170;
		this.txt.Name = "txt";
		this.txt.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
		this.txt.UseMarkup = true;
		this.txt.Wrap = true;
		this.txt.Selectable = true;
		this.fixed2.Add (this.txt);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.txt]));
		w8.X = 77;
		w8.Y = 53;
		this.Add (this.fixed2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 418;
		this.DefaultHeight = 316;
		this.Show ();
		this.o1.Clicked += new global::System.EventHandler (this.OnO1Clicked);
	}
}
